### ISSUE TITLE
消息的顺序性有处理吗？看起来不错，有什么其他开源实现的推荐吗？

### ISSUE THREAD

**Issue by 993198101** [OuYangLiang/libevent#7]
感觉star数少了，先试一下，我再找找其他的开源实现

**Comment by 993198101** [comment]
貌似只能单线程处理单个表

**Comment by OuYangLiang** [comment]
> 貌似只能单线程处理单个表

可以多个分表，不能多库。可以看看这里：
http://ouyblog.com/2018/08/%E5%9F%BA%E4%BA%8EKafka%E5%AE%9E%E7%8E%B0%E4%BA%8B%E4%BB%B6%E9%A9%B1%E5%8A%A8%E6%9E%B6%E6%9E%84

https://github.com/OuYangLiang/libevent-sample
